# Generated by Django 4.0.4 on 2022-07-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipeimage_image_alter_recipeimage_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/ingredients', verbose_name='Фото'),
        ),
    ]
